---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  become: yes
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    become: yes
  - name: write the apache config file
    template:
      src: file-only/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache
    become: yes
  - name: ensure apache is running
    service:
      name: httpd
      state: started
    become: yes
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
      become: yes  
